### ISSUE TITLE
File not found  - github.com/N4IRS/AllStar/raw/master/x86.tar.gz

### ISSUE THREAD

**Issue by N1EDD** [AllStarLink/DIAL#2]
This command in the x86_allstar_asterisk_install.sh script gives a file not found error; 

wget https://github.com/N4IRS/AllStar/raw/master/x86.tar.gz

**Comment by N4IRS** [comment]
This repository is deprecated. I am keeping it alive for historical purposes only. I will update the scripts over the next few weeks.  New repository is at https://github.com/AllStarLink/DIAL

73, Steve N4IRS
