### ISSUE TITLE
php5-cli has no installation candidate

### ISSUE THREAD

**Issue by rellim78** [AllStarLink/DIAL#7]
```
root@test:~# cat /proc/version 
Linux version 4.9.0-3-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18) ) #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06)
root@test:~# cat /etc/issue
Debian GNU/Linux 9 \n \l

root@test:~# 
```

required_libs.sh references php5-cli. Need to add backports to stretch, or use php-cli package.

**Comment by Bwtnet** [comment]
Yeah I second that as well, tried installing replacement but didn't work

**Comment by N4IRS** [comment]
I have not started working on Stretch yet.

**Comment by RichNeese** [comment]
I have been working on Stretch and moving to php7 as php5/6 is old . I should have a update soon.
the only thing is the repo  needs updating to stretch and new pkgs

**Comment by N4IRS** [comment]
I have tested the executables on Stretch and they are working except for 1 module. The issue with php5-cli is minor and will be addressed. Testing is being done on RPi Stretch with the apt-get install allstarlink.

**Comment by RichNeese** [comment]
ok well look at php7 and the issue should go away. as we upped it on a few projects including the OMV / OpenMediaVault and things work well

**Comment by N4IRS** [comment]
php7.0-cli works fine as a replacement on Stretch. The only reason for a php cli is to run astdb.php which is not used by AllStarLink itself. It is used by Allmon2.
