### ISSUE TITLE
Script fails to install DAHDI. 

### ISSUE THREAD

**Issue by KG5RKI** [AllStarLink/DIAL#9]
Dial iso also stalls during the dahdi compilation.  Tried manual compile which did work, installed it.  Reboot, still nothing in /dev/ and asterisk service fails to start.  Two other friends with same problem. 

[Feb 14 00:46:32] NOTICE[7276] cdr.c: CDR simple logging enabled.
[Feb 14 00:46:32] NOTICE[7276] loader.c: 54 modules will be loaded.
[Feb 14 00:46:32] ERROR[7276] chan_dahdi.c: Unable to load chan_dahdi.conf

hmm mayba this? lool fail https://i.gyazo.com/db1d0a54f05ee01d83dd0104a3fbc3a9.png

EDIT:

Wow your stuff is such a mess man, could not even track down the script that copies dahdi so I could setup a git pull and fix it.  Anyone with the problem, just copy the chan_dahdi.conf from here and put it in /etc/asterisk/ and your good to go... 

https://github.com/AllStarLink/DIAL/blob/master/configs/chan_dahdi.conf

**Comment by N4IRS** [comment]
Please learn how to report a problem.
